version: "3.0"
services:
  app:
    container_name: salesforce-automation
    build:
      context: .
    env_file: .env
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"