apiVersion: v1
kind: Service
metadata:
  name: |-
    {{ .Release.Name }}
  labels:
    name: |-
      {{ .Release.Name }}
  annotations: {}
spec:
  ports:
  - name: http
    port: 4041
    protocol: TCP
    targetPort: 4000
  - name: https
    port: 4040
    protocol: TCP
    targetPort: 4000
  selector:
    # This needs to match the selector in the RC/Deployment
    app: |-
      {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: |-
    {{ .Release.Name }}
  namespace: default
  labels:
    app: |-
      {{ .Release.Name }}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: |-
        {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: |-
          {{ .Release.Name }}
    spec:
      nodeSelector:
        kops.k8s.io/instancegroup: nodes
      containers:
      - name: |-
          {{ .Release.Name }}
        image: |-
          {{ .Values.repoUrl }}/salesforce-automation:{{ .Values.tag }}
        imagePullPolicy: Always 
        ports:
          - name: salesforce
            containerPort: 4000
            protocol: TCP
        resources:
          limits:
            cpu: |-
              {{ .Values.cpuLimit }}
            memory: |-
              {{ .Values.memoryLimit }}
          requests:
            cpu: |-
              {{ .Values.cpuRequest }}
            memory: |-
              {{ .Values.memoryRequest }}
        env:  
        - name: VWI_SERVICE_ENDPOINT
          value: |-
            {{ .Values.GRAPHQL_ENDPOINT }}
        - name: GRAPHQL_KEY
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: GRAPHQL_KEY
        - name: SALESFORCE_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SALESFORCE_ACCESS_TOKEN
        - name: SALESFORCE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SALESFORCE_CLIENT_ID
        - name: SALESFORCE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SALESFORCE_CLIENT_SECRET
        - name: SALESFORCE_INSTANCE_URL
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SALESFORCE_INSTANCE_URL
        - name: SALESFORCE_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SALESFORCE_REFRESH_TOKEN
        - name: SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: salesforce
              key: SERVER_KEY
